### ISSUE TITLE
Set up Scaffolding

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/react-project-scaffold#1]
# Motivation

We want to be able to use this as a scaffolding in case we are told to build a React app. 

# Task implementation
- [x] Initiate package
- [x] Bring in all the requirements
- [x] Install Scripts, including a run script
- [x] Run it to make sure it works
